version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        env_file:
            - .env
        depends_on:
            - mysql
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root_password_here # задайте свой пароль
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8080:8080"
        networks:
            - app-network

    vite:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vite
        working_dir: /var/www
        command: sh -c "npm install && npm run dev"
        volumes:
            - .:/var/www
            - /var/www/node_modules
        ports:
            - "5173:5173"
        depends_on:
            - app
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
